name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build react
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        cd Prod.Web    
        npm install
        npm run build
    - name: Build and push Docker image api
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ORG_DOCKER_USER }}
        password: ${{ secrets.ORG_DOCKER_PASS }}
        dockerfile: Prod.Api/Dockerfile
        repository: artsdatabanken/fab4api
        tags: latest
    - name: Post to slack
      run: ${{ secrets.POST_DEPLOY_FEEDBACK }}